services:
  - type: web
    name: mufra-fashions
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MAIL_SERVER
        value: smtp.sendgrid.net
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: "True"
      - key: MAIL_USE_SSL
        value: "False"
      - key: MAIL_USERNAME
        value: apikey
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        value: winnersb27@gmail.com
      - key: MONGO_URI
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false